[build]
  command = ""
  publish = "."

# Keep SW/manifest accessible when using SPA fallback
[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/manifest.webmanifest"
  to = "/manifest.webmanifest"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

